### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by wdpi** [cavi-au/Consent-O-Matic#101] opened 2022-09-18 20:47 UTC
`https://www.youtube.com/`

A cookie overlay pops up and stays there.

A checkmark appears on the Consent-O-Matic icon in the Firefox toolbar.

**Comment by xandro0777** [comment] 2022-09-18 21:39
Duplicate of #25

**Comment by svnhub** [comment] 2024-03-05 11:16
Closed as duplicate of #25

**Closed by svnhub** 2024-03-05 11:16 UTC
