### ISSUE TITLE
Opening settings on iOS opens empty tab

### ISSUE THREAD

**Issue by Obelisx** [cavi-au/Consent-O-Matic#338] opened 2023-07-29 13:27 UTC
There is no way for me to adjust the settings currently, as opening the settings results in an entirely black page. The extension is activated and has permissions granted. Disabling block pop-ups makes no difference. Using iOS 16.5.1 (20F75).

**Comment by Obelisx** [comment] 2023-07-29 13:45
Somehow it wasn’t turned on in the context menu (aA button). After enabling it there, the settings tab was able to open. However, now a lot of websites are broken, even after disabling the extension in settings. Some pages open completely black, whereas others have missing components.

**Comment by AdrienKaulmann** [comment] 2023-08-06 14:04
I have installed the extension on my I-pad from the apple app store.

Nothing seems wrong, but nothing seems to happen either. 

I can see the settings, but nothing in the context menu. From what I found so far, I understand there should be something in there. In Safari settings the extension is activated. After visiting various sites, including those in the rules list, I was obviously shown all kind of cookie consent pop-ups, but still have 0 counts of saved clicks.

How can I find out, whether consent-o-matic does anything at all or is there any other setting, I may have skipped? I just couldn’t find any information on consent-o-matic except for articles on how performing the extension was but not one single instruction on how to properly set it up and hope someone can help me to get started.

**Comment by svnhub** [comment] 2023-08-11 09:41
Not able to reproduce this, did it happen again to you after closing Safari?

**Comment by AdrienKaulmann** [comment] 2023-08-18 07:53
Hi,No that’s perfect now, I just could not spot the button. Now everything looks fine and I am amazed as privacy option for most sites are correctly selected.Good work and many thanksAdrien KaulmannSent from my iPadOn 11 Aug 2023, at 11:42, svnhub ***@***.***> wrote:﻿
Not able to reproduce this, did it happen again to you after closing Safari?

**Comment by svnhub** [comment] 2024-03-04 15:12
Exactly what happened here is a bit of mystery as it doesn't seem to happen even on a new install of Safari, so will have to close this issue for now. If it happens again or if you find a way to make this happen please reopen the issue!

**Closed by svnhub** 2024-03-04 15:12 UTC
