### ISSUE TITLE
Is Consent-O-Matic really an alternative to I don't care about cookies

### ISSUE THREAD

**Issue by pachainti** [cavi-au/Consent-O-Matic#91] opened 2022-09-16 06:00 UTC
Unfortunately for the community, Avast acquired [I don't care about cookies](https://www.i-dont-care-about-cookies.eu/) extension.
I have found on the web that your solution is probably the best to replace it I think it is a great opportunity for you to become a recommended extension on both mozilla add-on and chrome store.
However, I have tried using it and have already found some websites where it does not work such as google.com, youtube.com and others.
Why doesn't the extension work on them? Are they perhaps absent from the list?
Thank you

**Comment by qyz** [comment] 2022-09-16 06:28
I just read the message about [I don't care about cookies](https://www.i-dont-care-about-cookies.eu/) being acquired by Avast. By the way, Avast is in the process of [being bought by Symantec/Norton](https://en.wikipedia.org/wiki/Avast#:~:text=approved%20the%20proposed%20takeover%20by%20NortonLifeLock).

So all the trust that I have built up for IDCAC over the years is gone. Companies like these make acquisitions to make money. And I can't imagine a business model which would work for them and for us users.

@pachainti For me, Consent-O-Matic looks very promising. We should not come here and complain about missing sites and features. Instead we should try it help to improve Consent-O-Matic by adding support for more sites.

**Comment by pachainti** [comment] 2022-09-16 06:37
I agree with you on the acquisition and other things. However, I am not here to complain, but to help build an alternative to IDCAC. I have noticed that COM does not work well on many sites at the moment, so I am wondering if it could become a real alternative to IDCAC.

**Comment by toebeann** [comment] 2022-09-16 07:46
> I have tried using it and have already found some websites where it does not work such as google.com, youtube.com and others.
> Why doesn't the extension work on them? Are they perhaps absent from the list?

From my experience, IDCAC didn't work on Google either - I specifically remember having to manually set preferences for Google once I installed IDCAC and purged all cookies.

There are likely always going to be some websites that an automatic tool isn't going to be able to detect properly, as websites are not static. Their popups will change over time, and automated tools need to be updated manually to reflect these changes. IDCAC itself was being updated frequently for this reason. IDCAC also had the benefit of a large amount of financial support in the form of donations, enabling it's sole developer to focus on nothing but it's maintenance.

By contrast, the authors of COM are university staff, who likely have other things taking up their time during their days. But unlike IDCAC, the source is in a GitHub repository, which gives them the advantage of the wider open source community to help them maintain it.

> I am not here to complain, but to help build an alternative to IDCAC. I have noticed that COM does not work well on many sites at the moment, so I am wondering if it could become a real alternative to IDCAC.

I don't yet know if COM will become the de facto replacement for IDCAC - it's too early to tell. However, most users when looking for alternatives are ending up finding COM, and that is a good indication of where the majority are heading. I would expect in the coming weeks to see an influx of pull requests and issues, and how they are handled will also be a good indicator, but only time will tell what the FOSS replacement for IDCAC will be.

**Comment by pachainti** [comment] 2022-09-16 09:51
I agree with your comment except for this part:
> From my experience, IDCAC didn't work on Google either - I specifically remember having to manually set preferences for Google once I installed IDCAC and purged all cookies.
It works very well.

**Comment by cklokmose** [comment] 2022-09-16 12:26
Thank you for your interest in CoM! We can see the recent influx of users to CoM and are directing time and resources to accommodate the issues being reported.

**Comment by pachainti** [comment] 2022-09-17 13:47
For those interested, there is a [fork of IDCAC](https://github.com/OhMyGuus/I-Dont-Care-About-Cookies).

**Comment by Exagone313** [comment] 2022-09-18 19:29
Duplicate of #25

**Comment by svnhub** [comment] 2024-03-05 11:28
This issue ended up mostly a copy of the google.com discussion in #25 - closing as duplicate so we can focus on that

**Closed by svnhub** 2024-03-05 11:28 UTC
