### ISSUE TITLE
German translation: Word misspelled "ANZIEGE" (Anzeige)

### ISSUE THREAD

**Issue by raffisweb** [cavi-au/Consent-O-Matic#474] opened 2024-08-27 20:29 UTC
In the German translation (Safari, MacOS), the word “Anzeige” is misspelled in the settings. Unfortunately, this is very prominent and should be changed soon.

<img width="815" alt="Bildschirmfoto 2024-08-27 um 22 27 26" src="https://github.com/user-attachments/assets/c06f08cd-175e-4d3e-b9b8-d67f3c333021">

**Comment by jdreesen** [comment] 2024-08-27 20:50
Duplicate of #457, #453

**Comment by Paredroi** [comment] 2024-09-09 00:10
I have just noticed this with Windows and Firefox. The fix is indeed available and already merged into the master branch (on Jun 21). However, unfortunately there has been no new release since then (last version v1.1.0 from May 31).
IMO, the issue here can therefore be closed.

**Comment by svnhub** [comment] 2024-10-02 07:25
Indeed, we are in the process of releasing 1.1.3 where this issue is fixed - it should be available within a few weeks on all platforms

**Comment by svnhub** [comment] 2024-10-02 11:44
1.1.3 is available now and fixes this issue

**Closed by svnhub** 2024-10-02 11:44 UTC

**Comment by Paredroi** [comment] 2024-10-07 16:28
> 1.1.3 is available now and fixes this issue

Not according to mozilla.org:
![grafik](https://github.com/user-attachments/assets/d12f4d56-8228-4fcc-9703-e719b857b6fc)

**Comment by Paredroi** [comment] 2024-10-08 22:50
ofc i can wait. i mean after all this is a voluntary project. was just confused about “available now”.
